CREATE DATABASE IF NOT EXISTS reach17;
USE reach17;

CREATE TABLE IF NOT EXISTS tipologie_corso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS corso (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  id_tipologia INT NOT NULL,
  FOREIGN KEY (id_tipologia) REFERENCES tipologie_corso(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ateneo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS corso_ateneo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_corso INT NOT NULL,
  id_ateneo INT NOT NULL,
  UNIQUE (id_corso, id_ateneo),
  FOREIGN KEY (id_corso) REFERENCES corso(id) ON DELETE CASCADE,
  FOREIGN KEY (id_ateneo) REFERENCES ateneo(id) ON DELETE CASCADE
);
